# Generated by Django 5.1.3 on 2024-12-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cart_courses_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
