# Generated by Django 5.1.3 on 2024-12-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='in_carts', to='api.course'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_users', to='api.course'),
        ),
    ]
